### ISSUE TITLE
Postgres issue when running with compose

### ISSUE THREAD

**Issue by mareksyldatk** [netload-tech/netload-demo#8]
Relates to https://github.com/netload-tech/netload-demo/pull/6

When running `docker-compose up`, there seems to be some issue I guess with `postgres` init. 
eg. `scheduler` yields the following problem

```
scheduler    | Traceback (most recent call last):
scheduler    |   File "/usr/local/bin/airflow", line 32, in <module>
scheduler    |     args.func(args)
scheduler    |   File "/usr/local/lib/python3.6/site-packages/airflow/utils/cli.py", line 74, in wrapper
scheduler    |     return f(*args, **kwargs)
scheduler    |   File "/usr/local/lib/python3.6/site-packages/airflow/bin/cli.py", line 928, in scheduler
scheduler    |     job.run()
scheduler    |   File "/usr/local/lib/python3.6/site-packages/airflow/jobs.py", line 197, in run
scheduler    |     session.commit()
scheduler    |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 927, in commit
scheduler    |     self.transaction.commit()
scheduler    |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 465, in commit
scheduler    |     self._assert_active(prepared_ok=True)
scheduler    |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
scheduler    |     % self._rollback_exception
scheduler    | sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.OperationalError) could not connect to server: Connection refused
scheduler    | 	Is the server running on host "postgres" (192.168.0.3) and accepting
scheduler    | 	TCP/IP connections on port 5432?
```

**Comment by mareksyldatk** [comment]
Fixed with PR https://github.com/netload-tech/netload-demo/pull/9
